const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const rows = JSON.parse(fs.readFileSync(process.env.QUOTE_FIXTURE_PATH || path.join(root,'output/audit/corrected-ny-vegetables-2026-09-17.json')));
const context = {window:{agraxAPI:{},agraxUtil:{}}};
vm.runInNewContext(fs.readFileSync(path.join(root,'frontend/js/agrax-data.js'),'utf8'),context);
const skus = context.window.agraxData.skuRows(rows);
assert.equal(skus.length,379);
assert.equal(new Set(skus.map(s=>s.key)).size,379);
const find=(commodity,predicate=()=>true)=>skus.find(s=>s.raw.commodity===commodity&&predicate(s));
assert.equal(find('Peppers, Finger Hot',s=>s.variety==='Red').termTxt,'$48.00–$50.00');
assert.equal(find('Peppers, Finger Hot',s=>s.variety==='Green').termTxt,'$30.00');
assert.equal(find('Carrots',s=>s.raw.price_qualifier==='one lot').termTxt,'one lot $10.00');
assert.equal(find('Basil',s=>s.raw.price_mostly_low===26).termTxt,'$24.00–$30.00 · mostly $26.00–$28.00');
assert.ok(find('Jicama').quality.includes('35 lb reusable plastic container'));
assert.ok(find('Dry Eschallot',s=>s.raw.variety==='PEELED').quality.includes('Per jar'));
assert.ok(find('Tomatoes',s=>s.raw.variety==='MATURE GREENS').quality.toUpperCase().includes('85% U.S. ONE OR BETTER'));
console.log('Browse display: 379 distinct rows; golden price/color/grade/unit checks passed.');
