(function(){
'use strict';
const dialog=document.createElement('dialog');dialog.className='newsletter-dialog';dialog.setAttribute('aria-labelledby','newsletter-title');
dialog.innerHTML='<button class="newsletter-close" type="button" aria-label="Close">×</button><h2 id="newsletter-title">Your morning market reports</h2><p>Select the reports you want for each city.</p><form><label>Email address<input name="email" type="email" required maxlength="254" autocomplete="email"></label><div class="report-choices"></div><p>We’ll email a confirmation link. Daily report delivery is not active yet.</p><button class="newsletter-submit">Email my confirmation link</button><p class="newsletter-status" role="status"></p></form>';
document.body.append(dialog);window.reportChoices.render(dialog.querySelector('.report-choices'));let opener;
dialog.querySelector('.newsletter-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>opener?.focus());
document.addEventListener('click',e=>{const button=e.target.closest('[data-newsletter-open]');if(!button)return;opener=button;const email=button.parentElement.querySelector('input[type=email]');if(email?.value)dialog.querySelector('[name=email]').value=email.value;dialog.showModal();});
dialog.querySelector('form').addEventListener('submit',async e=>{e.preventDefault();const reports=window.reportChoices.read(dialog),status=dialog.querySelector('.newsletter-status'),button=dialog.querySelector('.newsletter-submit');if(!reports.length){status.textContent='Choose at least one report.';return;}button.disabled=true;status.textContent='Sending confirmation…';try{const result=await window.newsletterPost('request',{email:dialog.querySelector('[name=email]').value,reports});if(!result.confirmation_required)throw Error('Confirmation is unavailable.');status.textContent='Check your inbox and confirm your choices. Your subscription changes only after confirmation.';}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
})();
